-- return {
--     "nvim-pack/nvim-spectre",
--     dependecies = { "nvim-lua/plenary.nvim", "folke/trouble.nvim" },
--     event = "VeryLazy",
--     config = function()
--         local spectre = require "spectre"
--         spectre.setup {
--             default = { replace = { cmd = "sd" } },
--         }
--
--         vim.keymap.set("n", "<leader>S", function() spectre.toggle() end, {
--             desc = "Toggle Spectre",
--         })
--
--         vim.keymap.set("n", "<leader>sw", function() spectre.open_visual { select_word = true } end, {
--             desc = "Search current word",
--         })
--
--         vim.keymap.set("n", "<leader>sr", function() spectre.open_file_search() end, {
--             desc = "Search on current file",
--         })
--     end,
-- }
return {}
